ktor:
  application:
    modules:
      - ph.mart.shopper.ApplicationKt.module
  deployment:
    port: 8080
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/shopper"
  user: "postgres"
  password: "timeisgold7"

jwt:
  secret: "secret"
  issuer: "http://localhost/"
  audience: "http://localhost/"
  realm: "Access to 'hello'"