ktor:
  deployment:
    port: 8080
#    sslPort: 8443
  application:
    modules:
      - ph.mart.shopper.ApplicationKt.module
  security:
    ssl:
      keyStore: keystore.jks
      keyAlias: sampleAlias
      keyStorePassword: foobar
      privateKeyPassword: foobar
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://localhost:5432/shopper"
  user: "postgres"
  password: "timeisgold7"

jwt:
  secret: "secret"
  issuer: "http://localhost/"
  audience: "http://localhost/"
  realm: "Access to 'hello'"